version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    #### Uncomment to debug container ####
    # command: ["/bin/bash"] 
    # stdin_open: true         # Keep stdin open for interactive terminal
    # tty: true                # Allocate a pseudo-TTY for the shell