version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=1 # Enable debug mode
      - DATABASE_URL=postgresql://flask_user:flask_password@db:5432/flask_db
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - thumbnail_data:/app/backend/static/assets/thumbnails/processed
      - video_data:/app/backend/static/assets/videos/processed
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
    privileged: true

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
      POSTGRES_DB: flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  thumbnail_data:
  video_data:
